	"""#|----------Extra Functions----------|#"""
	# def ...
	

	'''#|--------------Getters--------------|#'''
		#this is where a list of getters will go...
	# def get_...


	'''#|--------------Setters--------------|#'''
		#this is where a list of setters will go...
	# def set_...
